// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOz_QaHyoRuRG3INy6JmNITGEePwxM88s',
    appId: '1:610208110773:web:b212b5f90148b6687846fc',
    messagingSenderId: '610208110773',
    projectId: 'brew-crew21',
    authDomain: 'brew-crew21.firebaseapp.com',
    storageBucket: 'brew-crew21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEhDIaxsxJpLpkaMPxge8U7W2i3iIAtlo',
    appId: '1:610208110773:android:679a202979d849317846fc',
    messagingSenderId: '610208110773',
    projectId: 'brew-crew21',
    storageBucket: 'brew-crew21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsk5faj6doHitmGBbPcz7OSYHETT6BHwc',
    appId: '1:610208110773:ios:dc8c834b5e255d997846fc',
    messagingSenderId: '610208110773',
    projectId: 'brew-crew21',
    storageBucket: 'brew-crew21.appspot.com',
    iosClientId: '610208110773-lkebpdepscubs37e6a07eoh3hjk4cufn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsk5faj6doHitmGBbPcz7OSYHETT6BHwc',
    appId: '1:610208110773:ios:dc8c834b5e255d997846fc',
    messagingSenderId: '610208110773',
    projectId: 'brew-crew21',
    storageBucket: 'brew-crew21.appspot.com',
    iosClientId: '610208110773-lkebpdepscubs37e6a07eoh3hjk4cufn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOz_QaHyoRuRG3INy6JmNITGEePwxM88s',
    appId: '1:610208110773:web:0eb36cdb445d06847846fc',
    messagingSenderId: '610208110773',
    projectId: 'brew-crew21',
    authDomain: 'brew-crew21.firebaseapp.com',
    storageBucket: 'brew-crew21.appspot.com',
  );
}
